title: Massively
bio: Jekyll version of the Massively theme by HTML5UP
description: Jekyll version of the Massively theme by HTML5UP
locale: en_US
baseurl: ''
url: ''
disqus_shortname: default
analytics-id: default
twitter: default
facebook: default
instagram: default
github: default
location: 'Los Angeles, CA'
phone: 310-318-5555
email: info@default.com
background_image: /images/bg.jpg
slapform_thankyou_page: /thank-you
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: '/blog/:title/'
      layout: post
      author: null
permalink: '/blog/:title/'
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
paginate: 6
paginate_path: '/blog/page:num/'
jekyll-mentions:
  base_url: 'https://github.com'
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - Rakefile
  - old
